name: Test Build

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install toolchain
      uses: fiam/arm-none-eabi-gcc@v1.0.4
      with:
        release: '10-2020-q4'
    - name: Build
      shell: bash
      run: cd firmware/ && ./build -M -w